-- ===== جاكيت التخرج: قاعدة بيانات Supabase =====
-- الصق هذا الملف كاملاً في SQL Editor ثم اضغط Run.
-- غيّر كلمة مرور المدير في السطر المحدد بالأسفل قبل التشغيل.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.orders (
  id          bigint generated by default as identity (start with 1001) primary key,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz,
  student     text not null,
  grade       text not null,
  phone       text not null,
  size        text not null,
  jacket_name text not null,
  number      text not null default '28',
  status      text not null default 'new' check (status in ('new','approved','edit','cancelled'))
);
create index if not exists orders_phone_idx on public.orders (phone);

create table if not exists public.app_settings (
  id         int primary key default 1 check (id = 1),
  data       jsonb not null default '{}'::jsonb,
  admin_hash text
);

-- لا أحد يصل للجدولين مباشرة؛ كل شيء عبر الدوال أدناه فقط
alter table public.orders        enable row level security;
alter table public.app_settings  enable row level security;
revoke all on public.orders, public.app_settings from anon, authenticated;

-- ===== الإعدادات الافتراضية =====
insert into public.app_settings (id, data) values (1, jsonb_build_object(
  'open', true,
  'closedMessage', 'باب الطلبات مغلق حالياً.',
  'maxChars', 8,
  'number', '28',
  'sizes', jsonb_build_array('S','M','L','XL','XXL'),
  'countryCode', '965',
  'title', 'جاكيت التخرج',
  'intro', 'اكتب الاسم أو الختم الذي ترغب بظهوره على ظهر الجاكيت، واختر مقاسك، ثم أرسل الطلب.',
  'approveMsg', E'السلام عليكم {student}،\nتم اعتماد طلبك لجاكيت التخرج:\nالاسم على الجاكيت: {name}\nالمقاس: {size}\nشكراً لك.',
  'editMsg', E'السلام عليكم {student}،\nنأمل تعديل الاسم المكتوب على الجاكيت ({name}) وإعادة إرسال الطلب من نفس الرابط برقم هاتفك نفسه.\nشكراً لك.'
)) on conflict (id) do nothing;

-- ===== كلمة مرور المدير (غيّر الكلمة بين علامتي الاقتباس) =====
update public.app_settings
   set admin_hash = extensions.crypt('ضع_كلمة_المرور_هنا', extensions.gen_salt('bf'))
 where id = 1;

-- ===== دوال مساعدة =====
create or replace function public._digits(t text) returns text
language sql immutable as $$
  select regexp_replace(translate(coalesce(t,''), '٠١٢٣٤٥٦٧٨٩۰۱۲۳۴۵۶۷۸۹', '01234567890123456789'), '\D', '', 'g')
$$;

create or replace function public._is_admin(k text) returns boolean
language plpgsql security definer set search_path = public, extensions as $$
declare h text;
begin
  select admin_hash into h from app_settings where id = 1;
  if h is null or k is null or k = '' then perform pg_sleep(0.4); return false; end if;
  if extensions.crypt(k, h) = h then return true; end if;
  perform pg_sleep(0.4);
  return false;
end $$;

create or replace function public._order_json(o public.orders) returns jsonb
language sql immutable as $$
  select jsonb_build_object('id', o.id, 'createdAt', o.created_at, 'student', o.student, 'grade', o.grade,
    'phone', o.phone, 'size', o.size, 'jacketName', o.jacket_name, 'number', o.number,
    'status', o.status, 'updatedAt', coalesce(o.updated_at::text, ''))
$$;

-- ===== للطلاب =====
create or replace function public.get_settings() returns jsonb
language sql security definer set search_path = public as $$
  select jsonb_build_object('ok', true, 'settings',
    jsonb_build_object('open', data->'open', 'closedMessage', data->'closedMessage', 'maxChars', data->'maxChars',
      'number', data->'number', 'sizes', data->'sizes', 'title', data->'title', 'intro', data->'intro'))
  from app_settings where id = 1
$$;

create or replace function public.submit_order(o jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  s jsonb; jn text; sz text; st text; gr text; ph text; ex orders; nid bigint;
begin
  select data into s from app_settings where id = 1;
  if not coalesce((s->>'open')::boolean, true) then
    return jsonb_build_object('ok', false, 'error', coalesce(s->>'closedMessage', 'باب الطلبات مغلق حالياً.'));
  end if;
  jn := btrim(coalesce(o->>'jacketName','')); sz := coalesce(o->>'size','');
  st := btrim(coalesce(o->>'student','')); gr := btrim(coalesce(o->>'grade','')); ph := public._digits(o->>'phone');
  if jn !~ '^[ء-غف-يـ ]+$' then return jsonb_build_object('ok', false, 'error', 'الاسم على الجاكيت يجب أن يكون بحروف عربية.'); end if;
  if char_length(jn) > coalesce((s->>'maxChars')::int, 8) then
    return jsonb_build_object('ok', false, 'error', 'الاسم أطول من الحد المسموح (' || (s->>'maxChars') || ' حروف).'); end if;
  if not (s->'sizes') ? sz then return jsonb_build_object('ok', false, 'error', 'المقاس غير متاح.'); end if;
  if char_length(st) < 3 or gr = '' or char_length(ph) <> 8 or char_length(st) > 80 or char_length(gr) > 40 then
    return jsonb_build_object('ok', false, 'error', 'بيانات التحقق غير مكتملة.'); end if;

  select * into ex from orders where phone = ph and status <> 'cancelled' order by id desc limit 1;
  if found then
    if ex.status <> 'edit' then
      return jsonb_build_object('ok', false, 'error', 'يوجد طلب مسجّل بهذا الرقم مسبقاً. للتعديل تواصل مع المشرف.'); end if;
    update orders set student = st, grade = gr, size = sz, jacket_name = jn, status = 'new', updated_at = now() where id = ex.id;
    return jsonb_build_object('ok', true, 'id', ex.id, 'updated', true);
  end if;
  insert into orders (student, grade, phone, size, jacket_name, number)
    values (st, gr, ph, sz, jn, coalesce(s->>'number','28')) returning id into nid;
  return jsonb_build_object('ok', true, 'id', nid);
end $$;

-- ===== للمدير =====
create or replace function public.admin_orders(k text) returns jsonb
language plpgsql security definer set search_path = public as $$
declare r jsonb;
begin
  if not public._is_admin(k) then return jsonb_build_object('ok', false, 'error', 'كلمة المرور غير صحيحة'); end if;
  select jsonb_build_object('ok', true,
    'orders', coalesce((select jsonb_agg(public._order_json(x) order by x.id) from orders x), '[]'::jsonb),
    'settings', (select data from app_settings where id = 1)) into r;
  return r;
end $$;

create or replace function public.admin_set_status(k text, oid bigint, st text) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if not public._is_admin(k) then return jsonb_build_object('ok', false, 'error', 'كلمة المرور غير صحيحة'); end if;
  if st not in ('new','approved','edit','cancelled') then return jsonb_build_object('ok', false, 'error', 'حالة غير صالحة'); end if;
  update orders set status = st, updated_at = now() where id = oid;
  if not found then return jsonb_build_object('ok', false, 'error', 'الطلب غير موجود'); end if;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.admin_delete_order(k text, oid bigint) returns jsonb
language plpgsql security definer set search_path = public as $$
declare cur text;
begin
  if not public._is_admin(k) then return jsonb_build_object('ok', false, 'error', 'كلمة المرور غير صحيحة'); end if;
  select status into cur from orders where id = oid;
  if cur is null then return jsonb_build_object('ok', false, 'error', 'الطلب غير موجود'); end if;
  if cur <> 'cancelled' then return jsonb_build_object('ok', false, 'error', 'لا يُحذف نهائياً إلا الطلب الملغي'); end if;
  delete from orders where id = oid;
  return jsonb_build_object('ok', true);
end $$;

create or replace function public.admin_save_settings(k text, s jsonb) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if not public._is_admin(k) then return jsonb_build_object('ok', false, 'error', 'كلمة المرور غير صحيحة'); end if;
  update app_settings set data = data || s where id = 1;
  return jsonb_build_object('ok', true);
end $$;

-- السماح باستدعاء الدوال العامة فقط
revoke all on function public._is_admin(text), public._digits(text), public._order_json(public.orders) from public, anon, authenticated;
grant execute on function public.get_settings(), public.submit_order(jsonb),
  public.admin_orders(text), public.admin_set_status(text, bigint, text),
  public.admin_delete_order(text, bigint), public.admin_save_settings(text, jsonb) to anon, authenticated;
